config/routes.rb
Cfadashboard::Application.routes.draw do
  
  match '/auth/:provider/callback' => 'authentications#create'
  resources :settings
  resources :authentications
  devise_for :users, :controllers => {:registrations => 'registrations'}
  root :to => "home#index"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  
  def provider_name
    if provider == 'open_id'
      "OpenID"
    else
      provider.titleize
    end
  end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :name, :setting
  scope :twitter_key, where(:name => "twitter_key")
  scope :twitter_secret, where(:name => "twitter_secret")
  scope :facebook_key, where(:name => "facebook_key")
  scope :facebook_secret, where(:name => "facebook_secret") 
  scope :github_key, where(:name => "github_key")
  scope :github_secret, where(:name => "github_secret") 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def apply_omniauth(omniauth)
    self.email = omniauth['user_info']['email'] if email.blank?
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end
  
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end
  
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      user.apply_omniauth(omniauth)
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end
  
  private
  
  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
    @settings = Setting.all
  end
  
  def show
    @setting = Setting.find(params[:id])
  end
  
  def new
    @setting = Setting.new
  end
  
  def create
    @setting = Setting.new(params[:setting])
    if @setting.save
      flash[:notice] = "Successfully created settings."
      redirect_to @setting
    else
      render :action => 'new'
    end
  end
  
  def edit
    @setting = Setting.find(params[:id])
  end
  
  def update
    @setting = Setting.find(params[:id])
    if @setting.update_attributes(params[:setting])
      flash[:notice] = "Successfully updated settings."
      redirect_to @setting
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy
    flash[:notice] = "Successfully destroyed settings."
    redirect_to settings_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
  

end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/authentications/_auth_menu.html.erb
<div id="auth_menu">
<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>

<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>
  Facebook
</a>

<a href="/auth/github" class="auth_provider">
  <%= image_tag "github_64.png", :size => "64x64", :alt => "Github" %>
  Github
</a>
</div>
<div style="clear:both;" />

app/views/authentications/index.html.erb
<% title "Your Linked Accounts" %>

<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authentication.provider.titleize %></div>
          <div class="uid"><%= authentication.uid %></div>
          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% end %>

<%= render 'auth_menu'%>

<div class="clear"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id ="user_nav">
          <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you? <%= link_to "Sign Out", destroy_user_session_path%>
          <% else %>
          <%= link_to "Sign Up", new_user_registration_path%> or <%= link_to "Sign In", new_user_session_path%>
          <% end %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/settings/_form.html.erb
<%= form_for @setting do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :setting %><br />
    <%= f.text_field :setting %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/settings/edit.html.erb
<% title "Edit Setting" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @setting %> |
  <%= link_to "View All", setting_path %>
</p>

app/views/settings/index.html.erb
<% title "Settings" %>

<table>
  <tr>
    <th>Name</th>
    <th>Setting</th>
  </tr>
  <% for setting in @settings %>
    <tr>
      <td><%= setting.name %></td>
      <td><%= setting.setting %></td>
      <td><%= link_to "Show", setting %></td>
      <td><%= link_to "Edit", edit_setting_path(setting) %></td>
      <td><%= link_to "Destroy", setting, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Setting", new_setting_path %></p>

app/views/settings/new.html.erb
<% title "New Settings" %>

<%= render 'form' %>

<p><%= link_to "Back to List", settings_path %></p>

app/views/settings/show.html.erb
<% title "Setting" %>

<p>
  <strong>Name:</strong>
  <%= @setting.name %>
</p>
<p>
  <strong>Setting:</strong>
  <%= @setting.setting %>
</p>

<p>
  <%= link_to "Edit", edit_setting_path(@setting) %> |
  <%= link_to "Destroy", @setting, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", settings_path %>
</p>